
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 11 22:04:07 PST 2017
//----------------------------------------------------

package org.pbrt.core;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OBJECTBEGIN = 27;
  public static final int CONCATTRANSFORM = 13;
  public static final int TRANSFORMEND = 40;
  public static final int LOOKAT = 21;
  public static final int WORLDEND = 45;
  public static final int COORDSYSTRANSFORM = 15;
  public static final int SAMPLER = 33;
  public static final int OBJECTINSTANCE = 29;
  public static final int PIXELFILTER = 30;
  public static final int TRANSFORMBEGIN = 39;
  public static final int TRANSLATE = 43;
  public static final int AREALIGHTSOURCE = 9;
  public static final int COORDINATESYSTEM = 14;
  public static final int NAMEDMATERIAL = 26;
  public static final int LIGHTSOURCE = 20;
  public static final int SHAPE = 35;
  public static final int EOF = 0;
  public static final int ATTRIBUTEBEGIN = 10;
  public static final int ROTATE = 32;
  public static final int error = 1;
  public static final int REVERSEORIENTATION = 31;
  public static final int INCLUDE = 19;
  public static final int NUMBER = 3;
  public static final int OBJECTEND = 28;
  public static final int STARTTIME = 36;
  public static final int INTEGRATOR = 37;
  public static final int ACTIVETRANSFORM = 7;
  public static final int LBRACK = 4;
  public static final int FILM = 17;
  public static final int TRANSFORMTIMES = 41;
  public static final int MEDIUMINTERFACE = 24;
  public static final int SCALE = 34;
  public static final int RBRACK = 5;
  public static final int WORLDBEGIN = 44;
  public static final int IDENTITY = 18;
  public static final int MAKENAMEDMATERIAL = 22;
  public static final int MATERIAL = 25;
  public static final int STRING = 2;
  public static final int ALL = 8;
  public static final int TEXTURE = 38;
  public static final int TRANSFORM = 42;
  public static final int ACCELERATOR = 6;
  public static final int CAMERA = 12;
  public static final int MAKENAMEDMEDIUM = 23;
  public static final int ENDTIME = 16;
  public static final int ATTRIBUTEEND = 11;
}

